version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      API_ENTRYPOINT: ${API_ENTRYPOINT}
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      SECRET_KEY: ${SECRET_KEY}
      JWT_SECRET: ${JWT_SECRET}
      REDIS_HOST: ${REDIS_HOST}
      DATABASE_URL: ${DATABASE_URL}
      GH_TOKEN: ${GH_TOKEN}
      SETUP_PASSWORD: ${SETUP_PASSWORD}
    depends_on:
      - redis-cache
      - database

  redis-cache:
    image: redis:alpine
    ports:
      - "6379"
    volumes:
     - redis_cache:/data

  database:
    image: postgres:alpine
    ports:
     - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  redis_cache: {}
  database: {}
