version: "3"

services:
  webapp:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      API_ENTRYPOINT: ${API_ENTRYPOINT}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      SECRET_KEY: ${SECRET_KEY}
      JWT_SECRET: ${JWT_SECRET}
      GH_TOKEN: ${GH_TOKEN}
      SETUP_PASSWORD: ${SETUP_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      DATABASE_URL: ${DATABASE_URL}
      YUBIKEY_CLIENT_ID: ${YUBIKEY_CLIENT_ID}
      YUBIKEY_CLIENT_SECRET: ${YUBIKEY_CLIENT_SECRET}
      ENV: production
      NODE_ENV: production
    depends_on:
      - database
    ports:
      - "4200:4200"

  database:
    image: postgres:alpine
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  database: {}
