# syntax=docker/dockerfile:1.3-labs
FROM node:lts-alpine as builder

WORKDIR /app

ENV NODE_OPTIONS="--max-old-space-size=8192"

COPY . .

RUN <<EOF
  apk --no-cache add libc6-compat
  npm i -g pnpm
  chown -R node:node /app
EOF

USER node

RUN <<EOF
  pnpm set store-dir $HOME/.pnpm-store
EOF

EXPOSE 4200

ENTRYPOINT ["./docker-entry.sh"]
