FROM node:lts-alpine as builder

ENV NODE_ENV development

WORKDIR /app

COPY . .

RUN apk add --no-cache --virtual .build-deps build-base python3 && \
  npm i -g pnpm && \
  pnpm i -g @nestjs/cli && \
  chown -R node:node /app

USER node

RUN pnpm set store-dir ~/.pnpm-store && \
  pnpm install --no-optional

EXPOSE 4200

ENTRYPOINT ["pnpm", "run", "start:dev"]
