FROM node:lts-alpine as builder

ENV NODE_ENV development

WORKDIR /app

COPY . .

RUN npm i -g pnpm && \
  pnpm i -g @nestjs/cli && \
  chown -R node:node /app

USER node

RUN pnpm set store-dir ~/.pnpm-store && \
  pnpm i --no-optional

EXPOSE 3000

ENTRYPOINT ["pnpm", "i", "--no-optional", "&&", "pnpm", "run", "start:dev"]
