template:
  path: website.yaml.j2
  type: file

parameters:
  DatabaseUrlArn: arn:aws:ssm:us-east-2:922147267922:parameter/production/database_url
  GHTokenArn: arn:aws:ssm:us-east-2:922147267922:parameter/production/gh_token
  JWTSecretArn: arn:aws:ssm:us-east-2:922147267922:parameter/production/jwt_secret
  PrivateSubnets:
    - !stack_output_external {{ stack_group_config.stack_prefix }}-vpc::PrivateSubnetA
    - !stack_output_external {{ stack_group_config.stack_prefix }}-vpc::PrivateSubnetB
  PublicSubnets: 
    - !stack_output_external {{ stack_group_config.stack_prefix }}-vpc::PublicSubnetA
    - !stack_output_external {{ stack_group_config.stack_prefix }}-vpc::PublicSubnetB
  RepositoryUri: !stack_output_external {{ stack_group_config.stack_prefix }}-ecr::RepositoryUri
  SecretKeyArn: arn:aws:ssm:us-east-2:922147267922:parameter/production/secret_key
  YubikeyClientIdArn: arn:aws:ssm:us-east-2:922147267922:parameter/production/yubikey_client_id
  YubikeyClientSecretArn: arn:aws:ssm:us-east-2:922147267922:parameter/production/yubikey_client_secret
  VpcId: !stack_output_external {{ stack_group_config.stack_prefix }}-vpc::VpcId