name: Build CI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

jobs:
  build_webapp:
    runs-on: ubuntu-latest
    environment: staging
    env:
      API_ENTRYPOINT: ${{secrets.API_ENTRYPOINT}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      JWT_SECRET: ${{secrets.JWT_SECRET}}
      GH_TOKEN: ${{secrets.GH_TOKEN}}
      SETUP_PASSWORD: ${{secrets.SETUP_PASSWORD}}
      ENV: 'production'
      NODE_ENV: 'production'
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v1

      - name: Log into container registery
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.4.0
        with:
          context: ./
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            DATABASE_URL=postgresql://${{secrets.POSTGRES_USER}}:${{secrets.POSTGRES_PASSWORD}}@postgres:5432/${{secrets.POSTGRES_DB}}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
