name: Build CI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

jobs:
  build_webapp:
    runs-on: ubuntu-latest
    environment: staging
    env:
      API_ENTRYPOINT: ${{secrets.API_ENTRYPOINT}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      JWT_SECRET: ${{secrets.JWT_SECRET}}
      REDIS_HOST: ${{secrets.REDIS_HOST}}
      REDIS_PORT: ${{secrets.REDIS_PORT}}
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      GH_TOKEN: ${{secrets.GH_TOKEN}}
      SETUP_PASSWORD: ${{secrets.SETUP_PASSWORD}}
      ENV: 'production'
      NODE_ENV: 'production'
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v1

      - name: Set up doctl
        run: digitalocean/action-doctl@v2
        with:
          token: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.4.0
        with:
          context: ./
          push: true
          tags: registry.digitalocean.com/quinnjr/quinnjr.tech_webapp:latest,registry.digitalocean.com/quinnjr/quinnjrtech_webapp:${{github.events.inputs.version}}
          build-args: |
            DATABASE_URL=postgresql://${{secrets.POSTGRES_USER}}:${{secrets.POSTGRES_PASSWORD}}@postgres:5432/quinnjr

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
